### ISSUE TITLE
Saliency maps generation

### ISSUE THREAD

**Issue by igor-davidyuk** [openvinotoolkit/model_api#176]
It would be great if Model API models had a method similar to the `postprocess`, that would generate a saliency map for models in any domain. Currently, we need to keep that logic on the GETi side. It exists in Mediapipe and serves the WEB UI and now I need to implement it in Python for GETi SDK. 
Including, for segmentation models, it would be nice to get activations before softmax, resulting in softer maps.
And preparing saliency maps for anomaly models as well.

**Comment by sovrasov** [comment]
@igor-davidyuk there are no plans to add XAI algorithms in MAPI. Only models with already integrated XAI modules are supported. Instead, we have a standalone project that can embed XAI branches into already generated IR models https://github.com/openvinotoolkit/openvino_xai
